# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- refs/tags/*

pr:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'SchildIccImporter.sln'
  buildConfiguration: 'Release'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        x64:
          buildPlatform: 'x64'
          dotnetPlatform: 'win-x64'

    steps:
    - checkout: self
      submodules: true

    - task: CmdLine@2
      displayName: Install gotnet-project-licenses
      inputs:
        script: dotnet tool install --global dotnet-project-licenses --version 2.0.0

    - task: CmdLine@2
      displayName: Create output directory
      inputs:
        script: mkdir output

    - task: NuGetToolInstaller@1
      displayName: Install nuget.exe

    - task: NuGetCommand@2
      displayName: Restore NuGet packages
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: Build Solution
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:RunWixToolsOutOfProc=true'   

    - task: CmdLine@2
      displayName: Copy and rename MSI
      inputs:
        script: copy SchildIccImporter.Installer\bin\$(buildPlatform)\Release\SchildIccImporter.Installer.msi output\setup-$(Build.SourceBranchName).msi
      condition: succeeded()

    - task: NuGetCommand@2
      displayName: 'nuget pack'
      inputs:
        command: pack
        packagesToPack: '**\*.nuspec'

    - task: CmdLine@2
      displayName: Copy NuPKG
      inputs:
        script: copy '$(Build.ArtifactStagingDirectory)\*.nupkg' output
      condition: succeeded()

    - task: PublishPipelineArtifact@1
      displayName: Publish MSI to artifacts
      inputs:
        targetPath: output
        artifactName: output

- stage: publish
  displayName: Publish
  dependsOn:
  - build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  jobs:
  - job: GitHub
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download artifacts

    - task: NuGetCommand@2
      displayName: 'Release to NuGet'
      inputs:
        command: push
        publishFeedCredentials: 'NuGet.org'
        nuGetFeedType: external
        packagesToPush: $(Agent.BuildDirectory)/output/*.nupkg

    - task: GitHubRelease@0
      displayName: Release to GitHub
      inputs:
        gitHubConnection: 'GitHub.com'
        repositoryName: schulit/schild-icc-importer
        assets: |
          $(Agent.BuildDirectory)/output/setup-*.msi
          $(Agent.BuildDirectory)/output/*.nupkg
      
