//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchildIccImporter.Gui {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class nlog : global::System.Configuration.ApplicationSettingsBase {
        
        private static nlog defaultInstance = ((nlog)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new nlog())));
        
        public static nlog Default {
            get {
                return defaultInstance;
            }
        }
    }
}
